# Generated by Django 5.1.6 on 2025-02-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_name_modelprovider_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regexrule',
            name='model_provider',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='RegexRule',
        ),
    ]
