# Generated by Django 5.1.6 on 2025-02-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_regexrule_model_provider_delete_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalResponseCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
