# Generated by Django 5.1.6 on 2025-02-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_globalresponsecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex_pattern', models.CharField(max_length=255)),
                ('original_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_rules', to='chatapp.modelprovider')),
                ('redirect_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_rules', to='chatapp.modelprovider')),
            ],
        ),
    ]
