# Generated by Django 5.1.6 on 2025-02-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_routingrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='original_model',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='routingrule',
            name='redirect_model',
            field=models.CharField(max_length=255),
        ),
    ]
